#ifndef DALI_BP2A_250605_031_A3_COMMON_H
#define DALI_BP2A_250605_031_A3_COMMON_H

#ifdef FAST_MODE
#ifndef FOPS_KERNEL_PAGE_SETUP_ATTEMPTS
#define FOPS_KERNEL_PAGE_SETUP_ATTEMPTS 32
#endif
#ifndef PIPE_MAX_ATTEMPTS
#define PIPE_MAX_ATTEMPTS 6
#endif
#ifndef PSELECT_ENTER_DELAY_USEC
#define PSELECT_ENTER_DELAY_USEC 25000
#endif
#ifndef ROUTE_WAIT_SECONDS
#define ROUTE_WAIT_SECONDS 5
#endif
#ifndef MAIN_ROUTE_START_DELAY_USEC
#define MAIN_ROUTE_START_DELAY_USEC 50000
#endif
#ifndef MAIN_ROUTE_POLL_USEC
#define MAIN_ROUTE_POLL_USEC 2000
#endif
#ifndef PIPE_PREPARE_POLL_USEC
#define PIPE_PREPARE_POLL_USEC 2000
#endif
#endif

#include "../../common.h"

#define SLIDE_BOOTID_LEAK_SOURCE \
  P0_DATA_ALIAS_CONST(KIMAGE_TEXT_BASE + SLIDE_BOOTID_LEAK_SOURCE_OFF)

#endif /* DALI_BP2A_250605_031_A3_COMMON_H */
